config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :polls, only: [:new, :create, :index, :show] do
  	resources :responses, only: [:new, :create]
  	resources :questions, only: [:new, :create]
  end

 
  root to: 'polls#index'
end

app/models/poll.rb
##
# Represents a single Poll instance.
# Cannot save an instance without a `title`.
#
# === Examples
# =>  	Poll.new(title: 'New title')
# =>    Poll.first.questions.all [<Question>, <Question>...]
#   

class Poll < ApplicationRecord
  validates :title, presence: true
  has_many :questions
  accepts_nested_attributes_for :questions
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
	# Creates a new form for a Poll instance.
	def new
		@poll = Poll.new
		@questions = @poll.questions.build
	end

	# Creates a new Poll instance from the parameters coming from the form.
	def create
		@poll = Poll.new(poll_params)
		if @poll.save
			redirect_to @poll
		else
			render :new
		end
	end

	# Lists all Poll instances.
	def index
    	@polls = Poll.all
  	end

  	# Shows a specific Poll instance.
  	def show
  		@poll = Poll.find(params[:id])
  		@questions = @poll.questions
  	end

  	# Defines required strong parameters to create a Poll.
  	private
    	def poll_params
      		params.require(:poll).permit(:title)
    	end

end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/index.html.erb
<div class="container pb-poll-wrap">
    <div class="row">
        <div class="col-md-12 col-md-offset-4">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3><strong>All Polls</strong></h3>
                </div>
                <div class="panel-body" style="padding: 0;">
                    <table class="table table-striped">
                        <tbody>
                        	<% @polls.each do |poll| -%>
		    					<tr>
		    						<td><%= link_to poll.title, poll %></td>
		    					</tr>
		  					<% end -%>
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                 
                    <button class="btn btn-warning pb-poll-items">
                    	<%= link_to 'Create a New Poll', [:new, :poll] %>
                    </button>
                    
                </div>
            </div>
        </div>
    </div>
</div>

app/views/polls/new.html.erb
<div class="container text-center">
  <h2>Create New Poll</h2>
  <%= bootstrap_form_for(@poll, local: true) do |form| %>
  <%= form.text_field :title, :placeholder=>"Poll Title"%>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@poll.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @poll.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <%= form.submit %>
<% end %>

</div>

app/views/polls/show.html.erb
<div class="container pb-poll-wrap">
    <div class="row">
        <div class="col-md-12 col-md-offset-4">
            <div class="panel panel-warning">
                <div class="panel-heading mt-4">
                    <h3><strong>"<%= @poll.title %>" Statistics</strong></h3>
                </div>
                <div class="panel-body" style="padding: 0;">
                    <table class="table table-striped">
                        <thead class="thead-dark">
                            <tr>
                              <th scope="col">Statistic Type</th>
                              <th scope="col">Number</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><strong># Of Questions</strong></td>
                                <td><p><%= @questions.size %></p></td>
                            </tr>
                            <tr>
                                <td><strong># Of Responses</strong></td>
                                <% if @questions[0].nil? %>
                                	<td><p>0</p></td>
                                <% else %>
                                	<td><p><%= @questions[0].responses.size %></p></td>
                                <% end %>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <br>
                <div class="panel-heading">
                    <h3><strong>"<%= @poll.title %>" Responses</strong></h3>
                </div>
                <div class="panel-body" style="padding: 0;">
                    <table class="table table-striped">
                        <thead class="thead-dark">
                            <tr>
                              <th scope="col">Question</th>
                              <th scope="col">Responses</th>
                            </tr>
                        </thead>
                        <tbody>
   							<% @questions.each do |question| %>
   								<tr>
   									<th scope="row"><%= question.title %></th>
   									<th scope="row"><%= question.submittable.breakdown %></th>
   								</tr>
   							<% end %>
                        </tbody>
                    </table>
                </div>
                <br>
                <div class="panel-footer">
                    <button class="btn btn-success pb-poll-items">
                    	<%= link_to 'Fill Out The Poll', new_poll_response_path(poll_id: @poll) %>
                    </button>
                    <button class="btn btn-warning pb-poll-items">
                    	<%= link_to('Add Multiple Choice Question', 
                    			    new_poll_question_path(
                    			    	@poll, 
                    			    	question: { 
                    			    		submittable_type: 'MultipleChoiceSubmittable' 
                    			    	}))%>
                    </button>
                    <button class="btn btn-warning pb-poll-items">
                    	<%= link_to('Add Open Ended Question', 
                    			    new_poll_question_path(
                    			    	@poll, 
                    			    	question: { 
                    			    		submittable_type: 'OpenSubmittable' 
                    			    	}))%>
                    </button>
                    <button class="btn btn-dark">
                    	<%= link_to 'Back', polls_path %>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>