config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :polls, only: [:new, :create, :index, :show] do
  	resources :responses, only: [:new, :create]
  	resources :questions, only: [:new, :create]
  end

 
  root to: 'polls#index'
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
    # Creates a new form for a Response
    # Helps the view to render Questions, so that a user can
    # submit an answer.
	def new
    	@poll = Poll.find(params[:poll_id])
    	@questions = @poll.questions
  	end

    # Creates a new Response instance, by parsing the form parameters.
    # Gets each key (question_#{id}), parses the question id from them,
    # and finds the related Question along with the text, to save a new Response.
	def create
    	@poll = Poll.find(params[:poll_id])
    	all_responses =  params.select{ |k,v| k.start_with? 'question' }
    	all_responses.each do |q, response|
    		question_id = q.split('_')[1]
    		question = Question.find(question_id)
    		response = Response.new(text: response, question: question)
    		response.save
    	end
    	redirect_to poll_path(params[:poll_id])
  	end

end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/new.html.erb
<div class="container text-center">
	<h1><strong>Title: </strong></h1>
	<h2><%= @poll.title %></h2>
	<br>
	<h1><strong>Questions: </strong></h1>
  <br>
  <%= form_with model: @response, url: poll_responses_path, local: true do |form| %>
	  <% @questions.each_with_index do |question, index| %>
	  		<p class="question-title"><%= index.next %> . <%= question.title %></p>
	  		<div class="form-group">
		    	<% if question.submittable_type == 'MultipleChoiceSubmittable'%>
			        <% question.submittable.options_for_form.each do |option| %>
	              	<%= form.radio_button :option, option.text, :value => option.text, name: "question_#{question.id}" %>
						   <%= label_tag(:option, option.text) %>
			      	<% end %>
			    <% else %>
			    	<%= form.text_area :text, name: "question_#{question.id}"%>
		      	<% end %>
		    </div>
	  <% end %>
	  <p>
	    <%= form.submit 'Submit'%>
	  </p>
  <% end %>

<button class="btn btn-dark">
    <%= link_to 'Back', poll_path(@poll.id) %>
</button>

</div>